source 'https://rubygems.org'

gem 'rspec'
gem 'guard-rspec', require: false

gem 'rest-client'
gem 'json'

# Install Growl via App Store
# Install GrowlNotify at http://growl.info/downloads.php
gem 'growl'